version: 0.1
os: linux
files:
  - source: /backend
    destination: /home/ubuntu/backend  # Adjust destination as needed
hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
